# Generated by Django 5.1.6 on 2025-05-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_common', models.CharField(max_length=100)),
                ('name_official', models.CharField(max_length=255)),
                ('native_name', models.TextField(blank=True, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.BigIntegerField()),
                ('area', models.FloatField()),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('coat_of_arms_url', models.URLField(blank=True, null=True)),
                ('cca2', models.CharField(max_length=3)),
                ('cca3', models.CharField(max_length=3)),
                ('cioc', models.CharField(blank=True, max_length=3, null=True)),
                ('fifa', models.CharField(blank=True, max_length=3, null=True)),
                ('timezones', models.CharField(max_length=200)),
                ('independent', models.BooleanField(default=False)),
                ('un_member', models.BooleanField(default=False)),
                ('start_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('landlocked', models.BooleanField(default=False)),
                ('tld', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_spellings', models.TextField(blank=True, null=True)),
                ('borders', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
