# Generated by Django 5.1.6 on 2025-05-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AlterField(
            model_name='country',
            name='name_common',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
