# Generated by Django 5.1.6 on 2025-05-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_remove_country_id_alter_country_name_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currencies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
