# Generated by Django 5.1.6 on 2025-05-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_country_currencies_country_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='currencies',
        ),
    ]
