# Generated by Django 5.1.6 on 2025-05-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
